"""
SQLite Database Layer
Provides an atomic, query-efficient store alongside the existing JSON files.

Tables
------
trades          — all paper trades (open + closed snapshots)
signals         — history of every signal generated by the AI engine
outcomes        — closed trade records with full indicator snapshot
refinements     — parameter change history
equity_curve    — portfolio value time-series (point per scheduler cycle)
sentiment_cache — cached sentiment results (replaces in-memory dict)

Usage
-----
    from modules.db import get_db
    db = get_db()
    db.insert_signal(signal_dict)
    db.insert_outcome(closed_trade_dict)

The database file lives at data/trading_bot.db (configurable via DB_PATH env var).
"""
from __future__ import annotations

import json
import logging
import os
import sqlite3
import threading
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# Default path: backend/data/trading_bot.db
_DEFAULT_DB_PATH = Path(__file__).parent.parent / "data" / "trading_bot.db"
DB_PATH = Path(os.environ.get("TRADING_BOT_DB", str(_DEFAULT_DB_PATH)))

_DDL = """
PRAGMA journal_mode=WAL;
PRAGMA foreign_keys=ON;

CREATE TABLE IF NOT EXISTS trades (
    id              TEXT PRIMARY KEY,
    ticker          TEXT NOT NULL,
    type            TEXT,
    status          TEXT NOT NULL DEFAULT 'open',   -- open | closed
    entry_price     REAL,
    exit_price      REAL,
    shares          REAL,
    cost_basis      REAL,
    entry_date      TEXT,
    exit_date       TEXT,
    exit_reason     TEXT,
    pnl             REAL,
    pnl_pct         REAL,
    confidence      INTEGER,
    risk_level      TEXT,
    holding_period  TEXT,
    key_signals     TEXT,   -- JSON array
    indicators      TEXT,   -- JSON object (snapshot at entry)
    created_at      TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS signals (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    ticker          TEXT NOT NULL,
    signal          TEXT,           -- buy | sell | hold
    confidence      INTEGER,
    rationale       TEXT,
    sentiment_score REAL,
    timeframe_align TEXT,
    raw_json        TEXT,           -- full signal dict as JSON
    generated_at    TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS outcomes (
    id              TEXT PRIMARY KEY,
    ticker          TEXT NOT NULL,
    entry_price     REAL,
    exit_price      REAL,
    entry_date      TEXT,
    exit_date       TEXT,
    pnl             REAL,
    pnl_pct         REAL,
    result          TEXT,   -- profit | loss | breakeven
    exit_reason     TEXT,
    was_correct     INTEGER,        -- 1 | 0
    confidence      INTEGER,
    key_signals     TEXT,           -- JSON array
    indicators      TEXT,           -- JSON object
    recorded_at     TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS refinements (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    refinement_num  INTEGER,
    trades_analyzed INTEGER,
    reasoning       TEXT,
    params_before   TEXT,   -- JSON
    params_after    TEXT,   -- JSON
    win_rate        REAL,
    profit_factor   REAL,
    sharpe_ratio    REAL,
    refined_at      TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS equity_curve (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    value       REAL NOT NULL,
    cash        REAL,
    invested    REAL,
    recorded_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS sentiment_cache (
    ticker          TEXT PRIMARY KEY,
    score           REAL,
    label           TEXT,
    key_events      TEXT,   -- JSON array
    headlines       TEXT,   -- JSON array
    fetched_at      TEXT NOT NULL
);

-- Indices for common query patterns
CREATE INDEX IF NOT EXISTS idx_signals_ticker   ON signals(ticker);
CREATE INDEX IF NOT EXISTS idx_signals_date     ON signals(generated_at);
CREATE INDEX IF NOT EXISTS idx_outcomes_ticker  ON outcomes(ticker);
CREATE INDEX IF NOT EXISTS idx_outcomes_date    ON outcomes(exit_date);
CREATE INDEX IF NOT EXISTS idx_equity_date      ON equity_curve(recorded_at);
"""


class TradingDB:
    """Thread-safe SQLite wrapper for the trading bot."""

    def __init__(self, path: Path = DB_PATH) -> None:
        self._path = path
        self._path.parent.mkdir(parents=True, exist_ok=True)
        self._local = threading.local()
        self._init_schema()

    # ── Connection management ─────────────────────────────────────────────────

    def _conn(self) -> sqlite3.Connection:
        """Return a per-thread connection (WAL mode is safe for this)."""
        if not hasattr(self._local, "conn") or self._local.conn is None:
            self._local.conn = sqlite3.connect(
                str(self._path),
                check_same_thread=False,
                timeout=10,
            )
            self._local.conn.row_factory = sqlite3.Row
        return self._local.conn

    def _init_schema(self) -> None:
        conn = self._conn()
        conn.executescript(_DDL)
        conn.commit()
        logger.info("SQLite DB ready: %s", self._path)

    # ── Signals ───────────────────────────────────────────────────────────────

    def insert_signal(self, signal: dict[str, Any]) -> None:
        conn = self._conn()
        conn.execute(
            """INSERT INTO signals
               (ticker, signal, confidence, rationale, sentiment_score,
                timeframe_align, raw_json, generated_at)
               VALUES (?,?,?,?,?,?,?,?)""",
            (
                signal.get("ticker"),
                signal.get("signal"),
                signal.get("confidence"),
                signal.get("rationale", "")[:500],
                signal.get("sentiment_context", {}).get("score"),
                signal.get("timeframe_alignment"),
                json.dumps(signal, default=str)[:4096],
                datetime.now(timezone.utc).isoformat(),
            ),
        )
        conn.commit()

    def get_signals(self, ticker: str | None = None, limit: int = 100) -> list[dict]:
        conn = self._conn()
        if ticker:
            rows = conn.execute(
                "SELECT * FROM signals WHERE ticker=? ORDER BY generated_at DESC LIMIT ?",
                (ticker, limit),
            ).fetchall()
        else:
            rows = conn.execute(
                "SELECT * FROM signals ORDER BY generated_at DESC LIMIT ?",
                (limit,),
            ).fetchall()
        return [dict(r) for r in rows]

    # ── Outcomes ──────────────────────────────────────────────────────────────

    def insert_outcome(self, trade: dict[str, Any]) -> None:
        conn = self._conn()
        conn.execute(
            """INSERT OR REPLACE INTO outcomes
               (id, ticker, entry_price, exit_price, entry_date, exit_date,
                pnl, pnl_pct, result, exit_reason, was_correct, confidence,
                key_signals, indicators, recorded_at)
               VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
            (
                trade.get("id", ""),
                trade.get("ticker"),
                trade.get("entry_price"),
                trade.get("exit_price"),
                trade.get("entry_date"),
                trade.get("exit_date"),
                trade.get("pnl"),
                trade.get("pct_change"),
                trade.get("result"),
                trade.get("exit_reason"),
                1 if trade.get("was_correct") else 0,
                trade.get("confidence_at_entry"),
                json.dumps(trade.get("key_signals", [])),
                json.dumps(trade.get("indicators_at_entry", {}), default=str),
                datetime.now(timezone.utc).isoformat(),
            ),
        )
        conn.commit()

    def get_outcomes(self, limit: int = 500) -> list[dict]:
        conn = self._conn()
        rows = conn.execute(
            "SELECT * FROM outcomes ORDER BY exit_date DESC LIMIT ?", (limit,)
        ).fetchall()
        return [dict(r) for r in rows]

    # ── Equity curve ──────────────────────────────────────────────────────────

    def insert_equity_point(self, value: float, cash: float, invested: float) -> None:
        conn = self._conn()
        conn.execute(
            "INSERT INTO equity_curve (value, cash, invested, recorded_at) VALUES (?,?,?,?)",
            (value, cash, invested, datetime.now(timezone.utc).isoformat()),
        )
        conn.commit()

    def get_equity_curve(self, limit: int = 500) -> list[dict]:
        conn = self._conn()
        rows = conn.execute(
            "SELECT * FROM equity_curve ORDER BY recorded_at DESC LIMIT ?", (limit,)
        ).fetchall()
        return [dict(r) for r in reversed(rows)]

    # ── Refinements ───────────────────────────────────────────────────────────

    def insert_refinement(self, entry: dict[str, Any]) -> None:
        stats = entry.get("stats_at_refinement", {})
        conn  = self._conn()
        conn.execute(
            """INSERT INTO refinements
               (refinement_num, trades_analyzed, reasoning,
                params_before, params_after,
                win_rate, profit_factor, sharpe_ratio, refined_at)
               VALUES (?,?,?,?,?,?,?,?,?)""",
            (
                entry.get("refinement_number"),
                entry.get("trades_analyzed"),
                entry.get("reasoning", "")[:1000],
                json.dumps(entry.get("before", {})),
                json.dumps(entry.get("after", {})),
                stats.get("win_rate"),
                stats.get("profit_factor"),
                stats.get("sharpe_ratio"),
                datetime.now(timezone.utc).isoformat(),
            ),
        )
        conn.commit()

    # ── Sentiment cache ───────────────────────────────────────────────────────

    def upsert_sentiment(self, ticker: str, sentiment: dict[str, Any]) -> None:
        conn = self._conn()
        conn.execute(
            """INSERT OR REPLACE INTO sentiment_cache
               (ticker, score, label, key_events, headlines, fetched_at)
               VALUES (?,?,?,?,?,?)""",
            (
                ticker,
                sentiment.get("sentiment_score"),
                sentiment.get("sentiment_label"),
                json.dumps(sentiment.get("key_events", [])),
                json.dumps(sentiment.get("headlines", [])),
                datetime.now(timezone.utc).isoformat(),
            ),
        )
        conn.commit()

    def get_sentiment(self, ticker: str) -> dict | None:
        conn = self._conn()
        row  = conn.execute(
            "SELECT * FROM sentiment_cache WHERE ticker=?", (ticker,)
        ).fetchone()
        if row is None:
            return None
        d = dict(row)
        d["key_events"] = json.loads(d.get("key_events") or "[]")
        d["headlines"]  = json.loads(d.get("headlines") or "[]")
        return d

    # ── Analytics queries ─────────────────────────────────────────────────────

    def win_rate_by_signal(self) -> list[dict]:
        """
        Return win rate per key signal extracted from the JSON array column.
        Useful for rapid signal attribution queries.
        """
        conn  = self._conn()
        rows  = conn.execute("SELECT key_signals, was_correct FROM outcomes").fetchall()
        stats: dict[str, dict] = {}
        for row in rows:
            signals = json.loads(row["key_signals"] or "[]")
            for sig in signals:
                if sig not in stats:
                    stats[sig] = {"wins": 0, "total": 0}
                stats[sig]["total"] += 1
                if row["was_correct"]:
                    stats[sig]["wins"] += 1
        return [
            {
                "signal":   s,
                "win_rate": round(v["wins"] / v["total"] * 100, 1),
                "trades":   v["total"],
                "wins":     v["wins"],
            }
            for s, v in sorted(stats.items(), key=lambda x: -x[1]["wins"] / max(x[1]["total"], 1))
        ]


# ── Singleton accessor ────────────────────────────────────────────────────────

_db_instance: TradingDB | None = None
_db_lock = threading.Lock()


def get_db() -> TradingDB:
    """Return the process-wide TradingDB singleton (lazy-initialised)."""
    global _db_instance
    if _db_instance is None:
        with _db_lock:
            if _db_instance is None:
                _db_instance = TradingDB()
    return _db_instance
